# Generated by Django 5.2.3 on 2025-08-19 12:54

from django.db import migrations
def create_missing_agent_profiles(apps, schema_editor):
    User = apps.get_model("users", "User")
    AgentProfile = apps.get_model("properties", "AgentProfile")

    for user in User.objects.filter(role="agent"):
        AgentProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_lead_assigned_to'),
    ]

    operations = [
    ]
